debug: true

logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        web:
          servlet.DispatcherServlet: DEBUG
          client.RestTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: select 1
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

management:
  endpoints:
    enabled-by-default: true

server:
  port: ${SERVER_PORT}

example:
  property: I AM DEFAULT