debug: true

logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        web:
          servlet.DispatcherServlet: DEBUG
          client.RestTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: ${SERVER_PORT}